apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: ghcr.io/themerxitix/dotnovi:1.0.0
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: webapi-config
            - secretRef:
                name: webapi-secret